require('../handlers/test/status_bar_handler.test');
require('../handlers/test/bean_provider_definition.test');
require('../handlers/test/injected_deps_handler.test');
require('../handlers/test/go_to_spec_handler.test');
require('../handlers/test/find_bean_usage_handler.test');
require('../handlers/test/show_all_beans_handler.test');
require('../handlers/test/go_to_package_handler.test');
require('../handlers/test/generate_bean_handler.test');
require('../handlers/test/generate_package_handler.test');